### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by toonech** [fledware/GodotXUnit#1]
Couple of minor issues found during install:

- GodotXUnitApi project has a hard reference to a specific version of the GodotSharp DLL.
  - I'm not sure if you can fix that other than manually deleting the version out of the actual CSPROJ file.  That's what I had to do for it to be able to find the DLL.  `, Version=1.0.7482.11423, Culture=neutral, PublicKeyToken=null` is what I removed.
- GodotXUnitApi is targeting .NET Framework 4.8, my project created by Godot is 4.7.
  - Manually downgraded GodotXUnitApi to 4.7 with no issues.  Could not get solution to build until I downgraded this project.  

So far, that's the only issues I've come across.  I'll update if I run into more.

**Comment by rexfleischer** [comment]
Sorry, I didn't realize I wasn't watching this and didn't know a ticket was opened. Thanks for taking the time!

I'll put together a fix for this.
