### ISSUE TITLE
Cannot install, super annoyed right now

### ISSUE THREAD

**Issue by Pilvinen** [fledware/GodotXUnit#17]
Your documentation is absolutely useless.

Everything goes wrong in installing. Nothing works.

^--- This feedback is as useful as your documentation.

**Comment by rexfleischer** [comment]
Are there any errors or info you can give? If there isn't then, this this issue is also absolutely useless and can be closed.

**Comment by Pilvinen** [comment]
There's a ticket making great suggestions for the docs which has been open since early 2021. That took me a step further, but even with that extra information I couldn't get it working.

I would recommend creating a fresh project and then doing what ever you need to do to make it work. Assume zero knowledge and prior experience. And write down what you have to do to get things working - with examples - and update the readme.md.

Good luck.

**Comment by rexfleischer** [comment]
Thank you, that's a great suggestion.

For your information (and for other that may stumble on this), I'm planning on doing just that when godot 4 is stable.

**Comment by GeorgeS2019** [comment]
@Pilvinen 
We now have working Godot4 port
